### ISSUE TITLE
Cannot recognize kharma metric name

### ISSUE THREAD

**Issue by rndsrc** [AFD-Illinois/igrmonty#15]
`igrmonty` currently only recognize `header/metric=MMKS` as pole-derefined coordinates.  In `kharma`'s GRMHD dumps, although both `header/geom/mmks` and `header/geom/fmks` are included, `header/metric` is set to `FMKS`. 

Changing

    if ( strncmp(metric_name, "MMKS", 19) == 0 ) {

to

    if ( strncmp(metric_name, "MMKS", 19) == 0 || strncmp(metric_name, "FMKS", 19) == 0 ) {

in `model/iharm/model.c` fixes this temperately.

**Comment by gnwong** [comment]
Fixed with 94a3d28.

Thanks for noticing this. I didn't know that KHARMA had a different convention.
